name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PlatformIO
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install platformio

      - name: Git clone Tasmota
        run: |
          git clone -b 'v14.4.1' --single-branch --depth 1 https://github.com/arendst/Tasmota

      - name: Copy user_config_override.h
        run: |
          cp user_config_override.h Tasmota/tasmota/user_config_override.h

      - name: Build Tasmota
        run: |
          cd Tasmota
          platformio run -e esp32s2cdc # -e tasmota
          mkdir -p ../out/
          mv .pio/build/*/firmware.bin ../out/tasmota32s2cdc.bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: out/*
          retention-days: 1
