name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PlatformIO
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install platformio

      - name: Install dependencies
        run: |
          platformio lib install -f "https://github.com/arendst/Tasmota.git#v14.4.1"

      - name: Copy user_config_override.h
        run: |
          cp user_config_override.h tasmota/tasota/user_config_override.h

      - name: Build Tasmota
        run: |
          platformio run -e tasmota -c tasmota.ino

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tasmota.bin
          path: .pio/build/*/firmware.bin
          retention-days: 1
