name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PlatformIO
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install platformio

      - name: Git clone Tasmota
        run: |
          git clone -b 'v14.4.1' --single-branch --depth 1 https://github.com/arendst/Tasmota

      - name: Copy user_config_override.h and change xdrv_01_9_webserver.ino
        run: |
          # FIXME: Find a proper way to change just the URL portion of the OTA_URL
          sed -i -e 's|http://ota.tasmota.com/tasmota/release/|https://github.com/probonopd/custom-tasmota/releases/download/continuous/|g' platformio_tasmota_env.ini
          sed -i -e 's|http://ota.tasmota.com/tasmota/release/|https://github.com/probonopd/custom-tasmota/releases/download/continuous/|g' platformio_tasmota_env32.ini
          cp user_config_override.h Tasmota/tasmota/user_config_override.h
          sed -i -e "s|Theo Arends</a><br>|Theo Arends</a><br><a href=\"https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}\">https://github.com/${GITHUB_REPOSITORY}</a>|g" Tasmota/tasmota/tasmota_xdrv_driver/xdrv_01_9_webserver.ino

      - name: Build Tasmota
        run: |
          cd Tasmota
          platformio run -e tasmota32s2cdc # -e tasmota
          mkdir -p ../out/
          mv .pio/build/*/firmware.bin ../out/tasmota32s2cdc.bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: out/*
          retention-days: 1
