name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  tasmota:
    # Based on https://raw.githubusercontent.com/arendst/Tasmota/development/.github/workflows/Tasmota_build_master.yml
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Pull Tasmota
      run: |
        git init
        git remote add origin https://github.com/arendst/Tasmota/
        git pull origin development
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        pip install -U platformio
    - name: Customize Tasmota
      run: |
        cat > tasmota/user_config_override.h <<\EOF
        #ifndef _USER_CONFIG_OVERRIDE_H_
        #define _USER_CONFIG_OVERRIDE_H_
        #define WEBSERVER_ADVERTISE
        #define USE_PING
        #endif  // _USER_CONFIG_OVERRIDE_H_
        EOF
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota
        find ./build_output
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

