name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  tasmota:
    # Based on https://raw.githubusercontent.com/arendst/Tasmota/development/.github/workflows/Tasmota_build_master.yml
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - name: Pull Tasmota
      run: |
        git init
        git remote add origin https://github.com/arendst/Tasmota/
        git pull origin development
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        pip install -U platformio
    - name: Run PlatformIO for tasmota-minimal
      run: |
        platformio run -e tasmota-minimal
        find ./build_output
        mkdir -p ./out
        mv ./build_output/firmware/tasmota-minimal.bin.gz out/tasmota-minimal-$(git rev-parse --short HEAD).bin.gz
        mv ./build_output/firmware/tasmota-minimal.bin out/tasmota-minimal-$(git rev-parse --short HEAD).bin
    - name: Run PlatformIO for each configuration
      run: |
        git clone https://github.com/$GITHUB_REPOSITORY/
        sh -ex custom-tasmota/build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: tasmota
        path: ./out

