name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  tasmota:
    # Based on https://raw.githubusercontent.com/arendst/Tasmota/development/.github/workflows/Tasmota_build_master.yml
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - name: Pull Tasmota
      run: |
        git init
        git remote add origin https://github.com/arendst/Tasmota/
        git pull origin development
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        pip install -U platformio
    - name: Run PlatformIO for tasmota-minimal
      run: |
        platformio run -e tasmota-minimal
        find ./build_output
        mkdir -p ./out
        mv ./build_output/firmware/tasmota-minimal.bin.gz out/tasmota-minimal-$(git rev-parse --short HEAD).bin.gz
        mv ./build_output/firmware/tasmota-minimal.bin out/tasmota-minimal-$(git rev-parse --short HEAD).bin
    - name: Customize Tasmota
      run: |
        cat > tasmota/user_config_override.h <<\EOF
        #ifndef _USER_CONFIG_OVERRIDE_H_
        #define _USER_CONFIG_OVERRIDE_H_
        #define WEBSERVER_ADVERTISE
        #define USE_PING
        #endif  // _USER_CONFIG_OVERRIDE_H_
        EOF
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota
        find ./build_output
        mkdir -p ./out
        mv ./build_output/firmware/tasmota.bin.gz out/tasmota-advertise-ping-$(git rev-parse --short HEAD).bin.gz
        mv ./build_output/firmware/tasmota.bin out/tasmota-advertise-ping-$(git rev-parse --short HEAD).bin
        mv ./tasmota/user_config_override.h out/tasmota-advertise-ping-user_config_override.h
    - name: Customize Tasmota for SK6812
      run: |
        cat > tasmota/user_config_override.h <<\EOF
        #ifndef _USER_CONFIG_OVERRIDE_H_
        #define _USER_CONFIG_OVERRIDE_H_
        #define WEBSERVER_ADVERTISE
        #define USE_PING
        #define USE_WS2812_HARDWARE  NEO_HW_SK6812     
        #define USE_WS2812_CTYPE     NEO_GRBW           // Color type (NEO_RGB, NEO_GRB, NEO_BRG, NEO_RBG, NEO_RGBW, NEO_GRBW)
        #endif  // _USER_CONFIG_OVERRIDE_H_
        EOF
    - name: Run PlatformIO for SK6812
      run: |
        platformio run -e tasmota
        find ./build_output
        mkdir -p ./out
        mv ./build_output/firmware/tasmota.bin.gz out/tasmota-sk6812-advertise-ping-$(git rev-parse --short HEAD).bin.gz
        mv ./build_output/firmware/tasmota.bin out/tasmota-sk6812-advertise-ping-$(git rev-parse --short HEAD).bin
        mv ./tasmota/user_config_override.h out/tasmota-sk6812-advertise-ping-user_config_override.h
    - uses: actions/upload-artifact@v2
      with:
        name: tasmota
        path: ./out

